"""Initial schema - all 15 tables

Revision ID: ffd44c2a326f
Revises: 
Create Date: 2026-02-12 09:20:07.156329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffd44c2a326f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_event_id'), 'audit_log', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_table('cpt_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('facility_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('non_facility_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rvu_work', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rvu_practice', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rvu_malpractice', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('global_period', sa.String(length=5), nullable=True),
    sa.Column('bundled_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_outpatient_typical', sa.Boolean(), nullable=False),
    sa.Column('is_lab_diagnostic', sa.Boolean(), nullable=False),
    sa.Column('is_dme', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpt_reference_cpt_code'), 'cpt_reference', ['cpt_code'], unique=True)
    op.create_table('icd_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('valid_cpt_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gender_specific', sa.String(length=1), nullable=True),
    sa.Column('age_range_min', sa.Integer(), nullable=True),
    sa.Column('age_range_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd_reference_icd_code'), 'icd_reference', ['icd_code'], unique=True)
    op.create_table('investigation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=30), nullable=False),
    sa.Column('claim_id', sa.String(length=30), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=5), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('resolution_path', sa.String(length=30), nullable=True),
    sa.Column('resolution_notes', sa.String(length=2000), nullable=True),
    sa.Column('estimated_fraud_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recovery_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_cases_case_id'), 'investigation_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_investigation_cases_claim_id'), 'investigation_cases', ['claim_id'], unique=False)
    op.create_index(op.f('ix_investigation_cases_priority'), 'investigation_cases', ['priority'], unique=False)
    op.create_index(op.f('ix_investigation_cases_status'), 'investigation_cases', ['status'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('plan_id', sa.String(length=20), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('eligibility_start', sa.Date(), nullable=False),
    sa.Column('eligibility_end', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=True)
    op.create_table('ndc_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ndc_code', sa.String(length=15), nullable=False),
    sa.Column('proprietary_name', sa.String(length=200), nullable=False),
    sa.Column('nonproprietary_name', sa.String(length=200), nullable=False),
    sa.Column('dosage_form', sa.String(length=50), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=False),
    sa.Column('substance_name', sa.String(length=200), nullable=True),
    sa.Column('dea_schedule', sa.String(length=5), nullable=True),
    sa.Column('therapeutic_class', sa.String(length=100), nullable=True),
    sa.Column('avg_wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('generic_available', sa.Boolean(), nullable=False),
    sa.Column('generic_ndc', sa.String(length=15), nullable=True),
    sa.Column('generic_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndc_reference_ndc_code'), 'ndc_reference', ['ndc_code'], unique=True)
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chain_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pharmacy_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oig_excluded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_npi'), 'pharmacies', ['npi'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=20), nullable=True),
    sa.Column('practice_address', sa.String(length=300), nullable=True),
    sa.Column('practice_city', sa.String(length=100), nullable=True),
    sa.Column('practice_state', sa.String(length=2), nullable=False),
    sa.Column('practice_zip', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oig_excluded', sa.Boolean(), nullable=False),
    sa.Column('dea_registration', sa.String(length=20), nullable=True),
    sa.Column('dea_schedule', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_npi'), 'providers', ['npi'], unique=True)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=30), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('rules_triggered', sa.Integer(), nullable=False),
    sa.Column('rule_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('scored_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_batch_id'), 'risk_scores', ['batch_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_claim_id'), 'risk_scores', ['claim_id'], unique=True)
    op.create_index(op.f('ix_risk_scores_risk_level'), 'risk_scores', ['risk_level'], unique=False)
    op.create_table('rule_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=30), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=10), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_results_batch_id'), 'rule_results', ['batch_id'], unique=False)
    op.create_index(op.f('ix_rule_results_claim_id'), 'rule_results', ['claim_id'], unique=False)
    op.create_index(op.f('ix_rule_results_rule_id'), 'rule_results', ['rule_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('fraud_type', sa.String(length=20), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('detection_logic', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('benchmark_source', sa.String(length=50), nullable=True),
    sa.Column('implementation_priority', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_modified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=True)
    op.create_table('case_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_evidence_case_id'), 'case_evidence', ['case_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('medical_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('referring_provider_id', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('place_of_service', sa.String(length=5), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('cpt_modifier', sa.String(length=10), nullable=True),
    sa.Column('diagnosis_code_primary', sa.String(length=10), nullable=False),
    sa.Column('diagnosis_code_2', sa.String(length=10), nullable=True),
    sa.Column('diagnosis_code_3', sa.String(length=10), nullable=True),
    sa.Column('diagnosis_code_4', sa.String(length=10), nullable=True),
    sa.Column('amount_billed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_allowed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('length_of_stay', sa.Integer(), nullable=True),
    sa.Column('drg_code', sa.String(length=10), nullable=True),
    sa.Column('revenue_code', sa.String(length=10), nullable=True),
    sa.Column('plan_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['referring_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_claims_batch_id'), 'medical_claims', ['batch_id'], unique=False)
    op.create_index(op.f('ix_medical_claims_claim_id'), 'medical_claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_medical_claims_cpt_code'), 'medical_claims', ['cpt_code'], unique=False)
    op.create_index(op.f('ix_medical_claims_diagnosis_code_primary'), 'medical_claims', ['diagnosis_code_primary'], unique=False)
    op.create_index(op.f('ix_medical_claims_member_id'), 'medical_claims', ['member_id'], unique=False)
    op.create_index(op.f('ix_medical_claims_provider_id'), 'medical_claims', ['provider_id'], unique=False)
    op.create_index(op.f('ix_medical_claims_service_date'), 'medical_claims', ['service_date'], unique=False)
    op.create_table('pharmacy_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('prescriber_id', sa.Integer(), nullable=False),
    sa.Column('fill_date', sa.Date(), nullable=False),
    sa.Column('ndc_code', sa.String(length=15), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('drug_class', sa.String(length=100), nullable=True),
    sa.Column('is_generic', sa.Boolean(), nullable=False),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('dea_schedule', sa.String(length=5), nullable=True),
    sa.Column('quantity_dispensed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_supply', sa.Integer(), nullable=False),
    sa.Column('refill_number', sa.Integer(), nullable=False),
    sa.Column('amount_billed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_allowed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('copay', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('prescriber_npi', sa.String(length=10), nullable=False),
    sa.Column('pharmacy_npi', sa.String(length=10), nullable=False),
    sa.Column('prior_auth', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['prescriber_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_claims_batch_id'), 'pharmacy_claims', ['batch_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_claims_claim_id'), 'pharmacy_claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_pharmacy_claims_fill_date'), 'pharmacy_claims', ['fill_date'], unique=False)
    op.create_index(op.f('ix_pharmacy_claims_member_id'), 'pharmacy_claims', ['member_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_claims_ndc_code'), 'pharmacy_claims', ['ndc_code'], unique=False)
    op.create_index(op.f('ix_pharmacy_claims_pharmacy_id'), 'pharmacy_claims', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_claims_prescriber_id'), 'pharmacy_claims', ['prescriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_claims_prescriber_id'), table_name='pharmacy_claims')
    op.drop_index(op.f('ix_pharmacy_claims_pharmacy_id'), table_name='pharmacy_claims')
    op.drop_index(op.f('ix_pharmacy_claims_ndc_code'), table_name='pharmacy_claims')
    op.drop_index(op.f('ix_pharmacy_claims_member_id'), table_name='pharmacy_claims')
    op.drop_index(op.f('ix_pharmacy_claims_fill_date'), table_name='pharmacy_claims')
    op.drop_index(op.f('ix_pharmacy_claims_claim_id'), table_name='pharmacy_claims')
    op.drop_index(op.f('ix_pharmacy_claims_batch_id'), table_name='pharmacy_claims')
    op.drop_table('pharmacy_claims')
    op.drop_index(op.f('ix_medical_claims_service_date'), table_name='medical_claims')
    op.drop_index(op.f('ix_medical_claims_provider_id'), table_name='medical_claims')
    op.drop_index(op.f('ix_medical_claims_member_id'), table_name='medical_claims')
    op.drop_index(op.f('ix_medical_claims_diagnosis_code_primary'), table_name='medical_claims')
    op.drop_index(op.f('ix_medical_claims_cpt_code'), table_name='medical_claims')
    op.drop_index(op.f('ix_medical_claims_claim_id'), table_name='medical_claims')
    op.drop_index(op.f('ix_medical_claims_batch_id'), table_name='medical_claims')
    op.drop_table('medical_claims')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_case_evidence_case_id'), table_name='case_evidence')
    op.drop_table('case_evidence')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_rule_results_rule_id'), table_name='rule_results')
    op.drop_index(op.f('ix_rule_results_claim_id'), table_name='rule_results')
    op.drop_index(op.f('ix_rule_results_batch_id'), table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_index(op.f('ix_risk_scores_risk_level'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_claim_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_batch_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_providers_npi'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_pharmacies_npi'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_ndc_reference_ndc_code'), table_name='ndc_reference')
    op.drop_table('ndc_reference')
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_investigation_cases_status'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_priority'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_claim_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_case_id'), table_name='investigation_cases')
    op.drop_table('investigation_cases')
    op.drop_index(op.f('ix_icd_reference_icd_code'), table_name='icd_reference')
    op.drop_table('icd_reference')
    op.drop_index(op.f('ix_cpt_reference_cpt_code'), table_name='cpt_reference')
    op.drop_table('cpt_reference')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
