"""
Fraud scenario configuration — maps rule IDs to the fraud tags injected into synthetic data.
Used for verification: after seeding + rule evaluation, every rule should trigger on its tagged claims.
"""

# Maps rule_id → list of fraud tags that should trigger it
RULE_TO_FRAUD_TAGS = {
    # Medical rules
    "M1": ["M1_upcoding"],
    "M2": ["M2_unbundling"],
    "M3": ["M3_duplicate"],
    "M4": ["M4_phantom"],
    "M5": ["M5_kickback_referrer", "M5_kickback_receiver"],
    "M6": ["M6_medically_unnecessary"],  # Injected as part of M1 upcoding claims
    "M7": ["M7_collusion_patient"],
    "M8": ["M8_modifier"],
    "M9": ["M9_copay_waiver"],
    "M10": ["M10_misclass"],
    "M11": ["M11_dme"],
    "M12": ["M12_lab_abuse"],
    "M13": ["M13_ghost"],
    "M14": ["M14_double_dip"],
    "M15": ["M15_telehealth"],
    "M16": ["M16_chart_padding"],
    # Pharmacy rules
    "P1": ["P1_forgery"],
    "P2": ["P2_doctor_shopping"],
    "P3": ["P3_pharmacy_shopping"],
    "P4": ["P4_early_refill"],
    "P5": ["P5_diversion"],
    "P6": ["P6_phantom", "P6_phantom_rx_only"],
    "P7": ["P7_substitution"],
    "P8": ["P8_kickback", "P8_kickback_rx"],
    "P9": ["P9_invalid_prescriber"],
    "P10": ["P10_stockpiling"],
    "P11": ["P11_compound"],
    "P12": ["P12_phantom_member"],
    "P13": ["P13_collusion"],
}

# Expected minimum counts of fraudulent claims per rule
EXPECTED_FRAUD_COUNTS = {
    "M1": 150,
    "M2": 60,
    "M3": 80,
    "M4": 40,
    "M5": 100,
    "M6": 50,
    "M7": 30,
    "M8": 100,
    "M9": 150,
    "M10": 40,
    "M11": 20,
    "M12": 150,
    "M13": 30,
    "M14": 20,
    "M15": 80,
    "M16": 60,
    "P1": 20,
    "P2": 60,
    "P3": 40,
    "P4": 150,
    "P5": 100,
    "P6": 40,
    "P7": 80,
    "P8": 80,
    "P9": 15,
    "P10": 40,
    "P11": 20,
    "P12": 30,
    "P13": 60,
}

# All 29 rules with their metadata for seeding into the rules table
RULES_SEED = [
    # ── Medical Rules ──
    {"rule_id": "M1", "category": "Upcoding", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "CPT/HCPCS code billed higher than expected based on diagnosis and CMS fee schedule benchmarks",
     "detection_logic": "amount_billed > CMS_expected × (1 + threshold_pct) AND amount_billed - CMS_expected > min_dollar",
     "weight": 9.0, "implementation_priority": "HIGH",
     "thresholds": {"percent_over": 20, "min_dollar_amount": 300, "benchmark": "CMS_fee_schedule"},
     "benchmark_source": "CMS_fee_schedule"},

    {"rule_id": "M2", "category": "Unbundling", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Multiple CPT codes billed separately that should be a single bundled code",
     "detection_logic": "Multiple component codes on same date for same member that map to a single panel code",
     "weight": 7.5, "implementation_priority": "MEDIUM",
     "thresholds": {"min_component_count": 2, "lookback_days": 0},
     "benchmark_source": "CMS_fee_schedule"},

    {"rule_id": "M3", "category": "Duplicate Billing", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Same service billed twice with different claim IDs for same member, provider, and date",
     "detection_logic": "Two claims match on member_id + provider_id + cpt_code + service_date with different claim_ids",
     "weight": 8.0, "implementation_priority": "HIGH",
     "thresholds": {"exact_match": True, "exclude_modifiers": ["76", "77"]},
     "benchmark_source": None},

    {"rule_id": "M4", "category": "Phantom Billing", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Claims for services with no corroborating evidence of actual patient visit",
     "detection_logic": "Provider has < N other claims in 30d period AND member has no other claims within 7d window",
     "weight": 10.0, "implementation_priority": "HIGH",
     "thresholds": {"min_provider_claims_period": 5, "corroboration_window_days": 7},
     "benchmark_source": None},

    {"rule_id": "M5", "category": "Kickback/Self-Referral", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Provider refers disproportionate share of patients to a single entity (lab, imaging, etc.)",
     "detection_logic": "referral_concentration = claims_to_single_entity / total_referrals > threshold",
     "weight": 9.5, "implementation_priority": "MEDIUM",
     "thresholds": {"concentration_pct": 80, "min_referral_count": 10},
     "benchmark_source": None},

    {"rule_id": "M6", "category": "Medically Unnecessary", "fraud_type": "Waste", "claim_type": "medical",
     "description": "Procedure not clinically appropriate for the given diagnosis, gender, or age",
     "detection_logic": "CPT code NOT in valid_cpt_codes for primary ICD-10 diagnosis, or gender/age mismatch",
     "weight": 7.0, "implementation_priority": "MEDIUM",
     "thresholds": {"require_cpt_icd_match": True, "check_gender": True, "check_age": True},
     "benchmark_source": "ICD_CPT_mapping"},

    {"rule_id": "M7", "category": "Provider Collusion", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Two providers billing same member on same date with overlapping services and frequent co-billing",
     "detection_logic": "Different providers bill same member same date AND share > N patients overall",
     "weight": 6.5, "implementation_priority": "LOW",
     "thresholds": {"min_shared_patients": 5, "same_day_required": True},
     "benchmark_source": None},

    {"rule_id": "M8", "category": "Modifier Misuse", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Provider uses modifier 25 or 59 at rates far exceeding industry benchmarks",
     "detection_logic": "Provider modifier usage rate > threshold for modifier 25 (benchmark ~30%) or 59 (benchmark ~25%)",
     "weight": 5.5, "implementation_priority": "MEDIUM",
     "thresholds": {"modifier_25_max_pct": 40, "modifier_59_max_pct": 35, "min_claims_for_pattern": 20},
     "benchmark_source": None},

    {"rule_id": "M9", "category": "Copay Waiver", "fraud_type": "Abuse", "claim_type": "medical",
     "description": "Provider routinely waives copays (amount_billed equals amount_allowed on nearly all claims)",
     "detection_logic": "amount_billed == amount_allowed on > threshold% of claims over 6+ month period",
     "weight": 2.5, "implementation_priority": "LOW",
     "thresholds": {"waiver_pct": 90, "min_months": 6, "min_claims": 30},
     "benchmark_source": None},

    {"rule_id": "M10", "category": "Inpatient/Outpatient Misclassification", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Inpatient admission with very short stay for procedures typically done outpatient",
     "detection_logic": "place_of_service=21 AND length_of_stay <= 1 AND procedure is typically outpatient",
     "weight": 6.0, "implementation_priority": "MEDIUM",
     "thresholds": {"max_los_for_flag": 1, "outpatient_cpt_list": "from_reference"},
     "benchmark_source": "CMS_fee_schedule"},

    {"rule_id": "M11", "category": "DME Fraud", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "High-cost DME equipment claims for patients whose activity contradicts medical need",
     "detection_logic": "DME claim > threshold amount AND member has contradicting activity claims",
     "weight": 6.0, "implementation_priority": "MEDIUM",
     "thresholds": {"min_dme_amount": 1000, "check_contradicting_claims": True},
     "benchmark_source": None},

    {"rule_id": "M12", "category": "Lab/Diagnostic Abuse", "fraud_type": "Waste", "claim_type": "medical",
     "description": "Provider orders lab/diagnostic tests on abnormally high percentage of office visits",
     "detection_logic": "Provider lab order rate on office visits > threshold (industry norm ~40-50%)",
     "weight": 5.0, "implementation_priority": "MEDIUM",
     "thresholds": {"lab_rate_max_pct": 70, "min_visits_for_pattern": 20},
     "benchmark_source": None},

    {"rule_id": "M13", "category": "Provider Ghosting", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Claims submitted by providers who are inactive or on OIG exclusion list",
     "detection_logic": "Provider is_active=False OR oig_excluded=True but has recent claims",
     "weight": 7.0, "implementation_priority": "LOW",
     "thresholds": {"check_active_status": True, "check_oig_exclusion": True},
     "benchmark_source": "NPPES"},

    {"rule_id": "M14", "category": "Double Dipping", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Same service billed to multiple payers for the same patient and date",
     "detection_logic": "Same member + service_date + CPT but different plan_id values",
     "weight": 7.0, "implementation_priority": "MEDIUM",
     "thresholds": {"require_same_cpt": True, "require_same_date": True},
     "benchmark_source": None},

    {"rule_id": "M15", "category": "Telehealth Fraud", "fraud_type": "Fraud", "claim_type": "medical",
     "description": "Excessive telehealth visit volume or telehealth billed at in-person rates",
     "detection_logic": "Provider >N telehealth claims per day OR telehealth billed at non-facility rate",
     "weight": 6.0, "implementation_priority": "MEDIUM",
     "thresholds": {"max_telehealth_per_day": 40, "check_pricing": True},
     "benchmark_source": "CMS_fee_schedule"},

    {"rule_id": "M16", "category": "Chart Padding", "fraud_type": "Abuse", "claim_type": "medical",
     "description": "Excessive diagnosis codes per encounter to inflate complexity and reimbursement",
     "detection_logic": "Claim has > N distinct diagnosis codes (normal is 2-4 per encounter)",
     "weight": 4.0, "implementation_priority": "LOW",
     "thresholds": {"max_diagnosis_codes": 6, "specialty_overrides": {"oncology": 8, "internal_medicine": 6}},
     "benchmark_source": None},

    # ── Pharmacy Rules ──
    {"rule_id": "P1", "category": "Prescription Forgery", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Prescriber NPI does not exist in provider registry or is inactive",
     "detection_logic": "Prescriber NPI not found in providers table OR prescriber is_active=False",
     "weight": 8.0, "implementation_priority": "MEDIUM",
     "thresholds": {"check_active": True, "check_exists": True},
     "benchmark_source": "NPPES"},

    {"rule_id": "P2", "category": "Doctor Shopping", "fraud_type": "Abuse", "claim_type": "pharmacy",
     "description": "Member visits multiple prescribers for controlled substances within a rolling window",
     "detection_logic": "Member has > N unique prescribers for Schedule II-III drugs in rolling X-day window",
     "weight": 7.5, "implementation_priority": "MEDIUM",
     "thresholds": {"max_prescribers": 4, "window_days": 90, "dea_schedules": ["CII", "CIII"]},
     "benchmark_source": None},

    {"rule_id": "P3", "category": "Pharmacy Shopping", "fraud_type": "Abuse", "claim_type": "pharmacy",
     "description": "Member fills same drug at multiple pharmacies within a rolling window",
     "detection_logic": "Member fills same drug at > N unique pharmacies within X-day window",
     "weight": 3.0, "implementation_priority": "LOW",
     "thresholds": {"max_pharmacies": 3, "window_days": 60, "match_by": "generic_name"},
     "benchmark_source": None},

    {"rule_id": "P4", "category": "Early Refill", "fraud_type": "Waste", "claim_type": "pharmacy",
     "description": "Prescription refilled before expected based on days supply",
     "detection_logic": "days_since_last_fill < days_supply × threshold_pct for same member+drug",
     "weight": 4.5, "implementation_priority": "HIGH",
     "thresholds": {"early_pct": 75},
     "benchmark_source": None},

    {"rule_id": "P5", "category": "Controlled Substance Diversion", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Prescriber writes disproportionately high percentage of controlled substance prescriptions",
     "detection_logic": "Prescriber controlled substance Rx rate > threshold (normal ~15-25%)",
     "weight": 9.5, "implementation_priority": "MEDIUM",
     "thresholds": {"max_controlled_pct": 60, "min_prescriptions": 20, "dea_schedules": ["CII", "CIII"]},
     "benchmark_source": None},

    {"rule_id": "P6", "category": "Phantom Claims", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Pharmacy claims for members with no medical claims history or expired eligibility",
     "detection_logic": "Member has 0 medical claims in last X days OR eligibility has expired",
     "weight": 10.0, "implementation_priority": "HIGH",
     "thresholds": {"no_medical_claims_days": 180, "check_eligibility": True},
     "benchmark_source": None},

    {"rule_id": "P7", "category": "High-Cost Substitution", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Pharmacy dispenses brand-name drug when cheaper generic equivalent is available",
     "detection_logic": "is_generic=False AND generic_available=True AND cost_diff > threshold",
     "weight": 5.5, "implementation_priority": "MEDIUM",
     "thresholds": {"cost_diff_pct": 50, "require_generic_available": True},
     "benchmark_source": "NDC_directory"},

    {"rule_id": "P8", "category": "Kickback/Split Billing", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Prescriber sends disproportionate share of prescriptions to a single pharmacy",
     "detection_logic": "Prescriber referral concentration to single pharmacy > threshold",
     "weight": 6.5, "implementation_priority": "MEDIUM",
     "thresholds": {"concentration_pct": 80, "min_prescriptions": 15},
     "benchmark_source": None},

    {"rule_id": "P9", "category": "Invalid Prescriber", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Prescriber lacks DEA registration for controlled substances they prescribe",
     "detection_logic": "Controlled substance Rx but prescriber has no DEA registration or wrong schedule",
     "weight": 8.5, "implementation_priority": "HIGH",
     "thresholds": {"check_dea": True, "check_schedule_match": True},
     "benchmark_source": "NPPES"},

    {"rule_id": "P10", "category": "Stockpiling", "fraud_type": "Waste", "claim_type": "pharmacy",
     "description": "Member accumulates excess drug supply beyond expected usage",
     "detection_logic": "Cumulative days_supply in X-day window exceeds calendar days by factor of Y",
     "weight": 4.0, "implementation_priority": "LOW",
     "thresholds": {"window_days": 90, "max_supply_ratio": 1.5},
     "benchmark_source": None},

    {"rule_id": "P11", "category": "Compound Drug Fraud", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Compounding pharmacy billing excessively high amounts for compound medications",
     "detection_logic": "Claim from compounding pharmacy with amount > threshold",
     "weight": 7.0, "implementation_priority": "LOW",
     "thresholds": {"max_compound_amount": 3000},
     "benchmark_source": None},

    {"rule_id": "P12", "category": "Phantom Members", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Pharmacy claims for members whose eligibility has expired",
     "detection_logic": "Member eligibility_end < fill_date (no longer eligible on date of service)",
     "weight": 8.0, "implementation_priority": "HIGH",
     "thresholds": {"grace_period_days": 0},
     "benchmark_source": None},

    {"rule_id": "P13", "category": "Pharmacy-Provider Collusion", "fraud_type": "Fraud", "claim_type": "pharmacy",
     "description": "Specific pharmacy-prescriber pair generates abnormally high claim volume",
     "detection_logic": "Pharmacy-prescriber pair claim volume > N standard deviations above mean",
     "weight": 6.0, "implementation_priority": "LOW",
     "thresholds": {"std_dev_threshold": 3.0, "min_claims": 20},
     "benchmark_source": None},
]
